VOCAB_SIZE=256

# Model
NUM_LAYERS=8
HIDDEN_SIZE=512
FFN_HIDDEN_SIZE=2048
NUM_ATTENTION_HEADS=8
SEQ_LENGTH=1024
 
# Training
MICRO_BATCH_SIZE=16
TRAIN_ITERS=50

# LR schedule
LR=3e-4
LR_WARMUP_FRACTION=0.1
LR_DECAY_STYLE=WSD        # cosine | linear | constant
LR_DECAY_ITERS=10
MIN_LR=3e-5
LR_WSD_DECAY_STYLE=linear
WEIGHT_DECAY=1e-2
 
# Norm — edit to experiment
NORMALIZATION=RMSNorm  # LayerNorm       # LayerNorm | RMSNorm
 
ROTARY_PERCENT=1.0
ROTARY_BASE=10000

# Logging & checkpointing
LOG_INTERVAL=25
SAVE_INTERVAL=500
EVAL_INTERVAL=500
EVAL_ITERS=10